// SPDX-FileCopyrightText: 2026 Shaan Narendran <shaannaren06@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-only

// AUTO-GENERATED by scripts/sync_features.py. DO NOT EDIT MANUALLY
// Source of truth: observal_cli/features.py

/**
 * Maps feature names to the minimum version that supports them.
 * Used for version negotiation: when CLI and server are at different versions,
 * both degrade to min(cli, server) feature set.
 */
export const FEATURE_VERSIONS: Record<string, string> = {
	agentBuilder: "0.8.0",
	agentInsights: "0.7.0",
	agentSnapshots: "0.6.0",
	basicAgents: "0.5.0",
	bulkAgents: "0.6.0",
	componentVersions: "0.6.0",
	deviceAuth: "0.7.0",
	mcpRegistry: "0.5.0",
	reconcile: "0.7.0",
	selfUpgrade: "0.8.0",
	skills: "0.7.0",
	versionNegotiation: "0.8.0",
};

/**
 * Check if a feature is available at the given effective version.
 * effective = min(cli_version, server_version)
 */
export function isFeatureAvailable(
	feature: string,
	effectiveVersion: string,
): boolean {
	const minVersion = FEATURE_VERSIONS[feature];
	if (!minVersion) return true; // Unknown features assumed available
	return semverGte(effectiveVersion, minVersion);
}

/**
 * Simple semver >= comparison (major.minor.patch only).
 */
function semverGte(a: string, b: string): boolean {
	const pa = a.split(".").map(Number);
	const pb = b.split(".").map(Number);
	for (let i = 0; i < 3; i++) {
		const av = pa[i] || 0;
		const bv = pb[i] || 0;
		if (av > bv) return true;
		if (av < bv) return false;
	}
	return true; // equal
}
