# SPDX-FileCopyrightText: 2026 Hari Srinivasan <harisrini21@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only

"""global unique names

Revision ID: 010_global_unique_names
Revises: 009_insights_version_progress
Create Date: 2026-06-20 20:22:11.581867

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "010_global_unique_names"
down_revision = "009_insights_version_progress"
branch_labels = None
depends_on = None


_TABLES = (
    "agents",
    "hook_listings",
    "mcp_listings",
    "prompt_listings",
    "sandbox_listings",
    "skill_listings",
)


def _dedupe_names(table: str) -> None:
    op.execute(
        f"""
        WITH ranked AS (
            SELECT id,
                   name,
                   row_number() OVER (PARTITION BY name ORDER BY created_at ASC, id ASC) AS rn
            FROM {table}
        )
        UPDATE {table} AS target
        SET name = left(ranked.name || '-' || left(replace(target.id::text, '-', ''), 8), 255)
        FROM ranked
        WHERE target.id = ranked.id AND ranked.rn > 1
        """
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic, adjusted for duplicate cleanup ###
    op.drop_constraint(op.f("uq_agents_name_created_by"), "agents", type_="unique")
    for table in _TABLES:
        _dedupe_names(table)
    op.create_unique_constraint("uq_agents_name", "agents", ["name"])
    op.create_unique_constraint("uq_hook_listings_name", "hook_listings", ["name"])
    op.create_unique_constraint("uq_mcp_listings_name", "mcp_listings", ["name"])
    op.create_unique_constraint("uq_prompt_listings_name", "prompt_listings", ["name"])
    op.create_unique_constraint("uq_sandbox_listings_name", "sandbox_listings", ["name"])
    op.create_unique_constraint("uq_skill_listings_name", "skill_listings", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic, adjusted for duplicate cleanup ###
    op.drop_constraint("uq_skill_listings_name", "skill_listings", type_="unique")
    op.drop_constraint("uq_sandbox_listings_name", "sandbox_listings", type_="unique")
    op.drop_constraint("uq_prompt_listings_name", "prompt_listings", type_="unique")
    op.drop_constraint("uq_mcp_listings_name", "mcp_listings", type_="unique")
    op.drop_constraint("uq_hook_listings_name", "hook_listings", type_="unique")
    op.drop_constraint("uq_agents_name", "agents", type_="unique")
    op.create_unique_constraint(
        op.f("uq_agents_name_created_by"),
        "agents",
        ["name", "created_by"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
