"""Query VulnerableCode for known vulnerabilities in CycloneDX SBOM components."""

import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

VULNERABLECODE_API = "https://public.vulnerablecode.io/api/packages/bulk_search/"
BATCH_SIZE = 25


def bulk_query(purls: list[str], retries: int = 3) -> list[dict]:
    """Query VulnerableCode bulk endpoint for a batch of PURLs."""
    payload = json.dumps({"purls": purls}).encode()
    req = urllib.request.Request(
        VULNERABLECODE_API,
        data=payload,
        headers={"Content-Type": "application/json", "Accept": "application/json"},
    )
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read())
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
            if attempt < retries - 1:
                time.sleep(2**attempt)
            else:
                print(f"  Warning: bulk query failed after {retries} attempts: {e}")
    return []


def main():
    if len(sys.argv) < 2:
        print("Usage: check_vulnerabilities.py <sbom1.cdx.json> [sbom2.cdx.json ...]")
        sys.exit(0)

    all_purls = []
    for sbom_path in sys.argv[1:]:
        try:
            with open(sbom_path) as f:
                sbom = json.load(f)
            for comp in sbom.get("components", []):
                purl = comp.get("purl")
                if purl:
                    all_purls.append(purl)
        except (FileNotFoundError, json.JSONDecodeError) as e:
            print(f"Warning: could not read {sbom_path}: {e}")

    all_purls = sorted(set(all_purls))
    print(f"Checking {len(all_purls)} packages against VulnerableCode...")

    findings = []
    for i in range(0, len(all_purls), BATCH_SIZE):
        batch = all_purls[i : i + BATCH_SIZE]
        results = bulk_query(batch)
        for pkg in results:
            if pkg.get("affected_by_vulnerabilities"):
                for vuln in pkg["affected_by_vulnerabilities"]:
                    findings.append(
                        {
                            "purl": pkg.get("purl", ""),
                            "vulnerability_id": vuln.get("vulnerability_id", ""),
                            "summary": vuln.get("summary", "")[:100],
                            "url": vuln.get("url", ""),
                        }
                    )

    if findings:
        with open("vulnerability-report.md", "w") as f:
            f.write("# SBOM Vulnerability Report\n\n")
            f.write(f"Found **{len(findings)}** known vulnerability(ies) across dependencies.\n\n")
            f.write("| Package | Vulnerability | Summary |\n")
            f.write("|---------|--------------|--------|\n")
            for item in findings:
                summary = item["summary"].replace("|", "\\|")
                f.write(f"| `{item['purl']}` | [{item['vulnerability_id']}]({item['url']}) | {summary} |\n")
            f.write(
                "\n---\n*Generated by CI. Non-blocking advisory via "
                "[VulnerableCode](https://public.vulnerablecode.io)*\n"
            )
        print(f"::warning::Found {len(findings)} known vulnerabilities. Report saved.")
    else:
        print("No known vulnerabilities found.")


if __name__ == "__main__":
    main()
