/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedLeaderboardRouteImport } from './routes/_authed/leaderboard'
import { Route as AuthedUserRouteImport } from './routes/_authed/_user'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authDeviceRouteImport } from './routes/(auth)/device'
import { Route as AuthedWikiIndexRouteImport } from './routes/_authed/wiki/index'
import { Route as AuthedComponentsIndexRouteImport } from './routes/_authed/components/index'
import { Route as AuthedAgentsIndexRouteImport } from './routes/_authed/agents/index'
import { Route as AuthedInsightsReportIdRouteImport } from './routes/_authed/insights/$reportId'
import { Route as AuthedComponentsComponentIdRouteImport } from './routes/_authed/components/$componentId'
import { Route as AuthedAgentsBuilderRouteImport } from './routes/_authed/agents/builder'
import { Route as AuthedAgentsAgentIdRouteImport } from './routes/_authed/agents/$agentId'
import { Route as AuthedUserAccountRouteImport } from './routes/_authed/_user/account'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/_admin/users'
import { Route as AuthedAdminSsoRouteImport } from './routes/_authed/_admin/sso'
import { Route as AuthedAdminSettingsRouteImport } from './routes/_authed/_admin/settings'
import { Route as AuthedAdminSecurityEventsRouteImport } from './routes/_authed/_admin/security-events'
import { Route as AuthedAdminReviewRouteImport } from './routes/_authed/_admin/review'
import { Route as AuthedAdminErrorsRouteImport } from './routes/_authed/_admin/errors'
import { Route as AuthedAdminDiagnosticsRouteImport } from './routes/_authed/_admin/diagnostics'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/_admin/dashboard'
import { Route as AuthedAdminAuditLogRouteImport } from './routes/_authed/_admin/audit-log'
import { Route as authInviteTokenRouteImport } from './routes/(auth)/invite.$token'
import { Route as AuthedUserTracesIndexRouteImport } from './routes/_authed/_user/traces/index'
import { Route as AuthedUserTracesTraceIdRouteImport } from './routes/_authed/_user/traces/$traceId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaderboardRoute = AuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserRoute = AuthedUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authDeviceRoute = authDeviceRouteImport.update({
  id: '/(auth)/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWikiIndexRoute = AuthedWikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComponentsIndexRoute = AuthedComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsIndexRoute = AuthedAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInsightsReportIdRoute = AuthedInsightsReportIdRouteImport.update({
  id: '/insights/$reportId',
  path: '/insights/$reportId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComponentsComponentIdRoute =
  AuthedComponentsComponentIdRouteImport.update({
    id: '/components/$componentId',
    path: '/components/$componentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAgentsBuilderRoute = AuthedAgentsBuilderRouteImport.update({
  id: '/agents/builder',
  path: '/agents/builder',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsAgentIdRoute = AuthedAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserAccountRoute = AuthedUserAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedUserRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminSsoRoute = AuthedAdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminSettingsRoute = AuthedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminSecurityEventsRoute =
  AuthedAdminSecurityEventsRouteImport.update({
    id: '/security-events',
    path: '/security-events',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminReviewRoute = AuthedAdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminErrorsRoute = AuthedAdminErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminDiagnosticsRoute = AuthedAdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminAuditLogRoute = AuthedAdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const authInviteTokenRoute = authInviteTokenRouteImport.update({
  id: '/(auth)/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUserTracesIndexRoute = AuthedUserTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => AuthedUserRoute,
} as any)
const AuthedUserTracesTraceIdRoute = AuthedUserTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => AuthedUserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/device': typeof authDeviceRoute
  '/login': typeof authLoginRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/invite/$token': typeof authInviteTokenRoute
  '/audit-log': typeof AuthedAdminAuditLogRoute
  '/dashboard': typeof AuthedAdminDashboardRoute
  '/diagnostics': typeof AuthedAdminDiagnosticsRoute
  '/errors': typeof AuthedAdminErrorsRoute
  '/review': typeof AuthedAdminReviewRoute
  '/security-events': typeof AuthedAdminSecurityEventsRoute
  '/settings': typeof AuthedAdminSettingsRoute
  '/sso': typeof AuthedAdminSsoRoute
  '/users': typeof AuthedAdminUsersRoute
  '/account': typeof AuthedUserAccountRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/agents/builder': typeof AuthedAgentsBuilderRoute
  '/components/$componentId': typeof AuthedComponentsComponentIdRoute
  '/insights/$reportId': typeof AuthedInsightsReportIdRoute
  '/agents/': typeof AuthedAgentsIndexRoute
  '/components/': typeof AuthedComponentsIndexRoute
  '/wiki/': typeof AuthedWikiIndexRoute
  '/traces/$traceId': typeof AuthedUserTracesTraceIdRoute
  '/traces/': typeof AuthedUserTracesIndexRoute
}
export interface FileRoutesByTo {
  '/device': typeof authDeviceRoute
  '/login': typeof authLoginRoute
  '/': typeof AuthedIndexRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/invite/$token': typeof authInviteTokenRoute
  '/audit-log': typeof AuthedAdminAuditLogRoute
  '/dashboard': typeof AuthedAdminDashboardRoute
  '/diagnostics': typeof AuthedAdminDiagnosticsRoute
  '/errors': typeof AuthedAdminErrorsRoute
  '/review': typeof AuthedAdminReviewRoute
  '/security-events': typeof AuthedAdminSecurityEventsRoute
  '/settings': typeof AuthedAdminSettingsRoute
  '/sso': typeof AuthedAdminSsoRoute
  '/users': typeof AuthedAdminUsersRoute
  '/account': typeof AuthedUserAccountRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/agents/builder': typeof AuthedAgentsBuilderRoute
  '/components/$componentId': typeof AuthedComponentsComponentIdRoute
  '/insights/$reportId': typeof AuthedInsightsReportIdRoute
  '/agents': typeof AuthedAgentsIndexRoute
  '/components': typeof AuthedComponentsIndexRoute
  '/wiki': typeof AuthedWikiIndexRoute
  '/traces/$traceId': typeof AuthedUserTracesTraceIdRoute
  '/traces': typeof AuthedUserTracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/(auth)/device': typeof authDeviceRoute
  '/(auth)/login': typeof authLoginRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/_user': typeof AuthedUserRouteWithChildren
  '/_authed/leaderboard': typeof AuthedLeaderboardRoute
  '/_authed/': typeof AuthedIndexRoute
  '/(auth)/invite/$token': typeof authInviteTokenRoute
  '/_authed/_admin/audit-log': typeof AuthedAdminAuditLogRoute
  '/_authed/_admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/_admin/diagnostics': typeof AuthedAdminDiagnosticsRoute
  '/_authed/_admin/errors': typeof AuthedAdminErrorsRoute
  '/_authed/_admin/review': typeof AuthedAdminReviewRoute
  '/_authed/_admin/security-events': typeof AuthedAdminSecurityEventsRoute
  '/_authed/_admin/settings': typeof AuthedAdminSettingsRoute
  '/_authed/_admin/sso': typeof AuthedAdminSsoRoute
  '/_authed/_admin/users': typeof AuthedAdminUsersRoute
  '/_authed/_user/account': typeof AuthedUserAccountRoute
  '/_authed/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/_authed/agents/builder': typeof AuthedAgentsBuilderRoute
  '/_authed/components/$componentId': typeof AuthedComponentsComponentIdRoute
  '/_authed/insights/$reportId': typeof AuthedInsightsReportIdRoute
  '/_authed/agents/': typeof AuthedAgentsIndexRoute
  '/_authed/components/': typeof AuthedComponentsIndexRoute
  '/_authed/wiki/': typeof AuthedWikiIndexRoute
  '/_authed/_user/traces/$traceId': typeof AuthedUserTracesTraceIdRoute
  '/_authed/_user/traces/': typeof AuthedUserTracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/login'
    | '/leaderboard'
    | '/invite/$token'
    | '/audit-log'
    | '/dashboard'
    | '/diagnostics'
    | '/errors'
    | '/review'
    | '/security-events'
    | '/settings'
    | '/sso'
    | '/users'
    | '/account'
    | '/agents/$agentId'
    | '/agents/builder'
    | '/components/$componentId'
    | '/insights/$reportId'
    | '/agents/'
    | '/components/'
    | '/wiki/'
    | '/traces/$traceId'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/device'
    | '/login'
    | '/'
    | '/leaderboard'
    | '/invite/$token'
    | '/audit-log'
    | '/dashboard'
    | '/diagnostics'
    | '/errors'
    | '/review'
    | '/security-events'
    | '/settings'
    | '/sso'
    | '/users'
    | '/account'
    | '/agents/$agentId'
    | '/agents/builder'
    | '/components/$componentId'
    | '/insights/$reportId'
    | '/agents'
    | '/components'
    | '/wiki'
    | '/traces/$traceId'
    | '/traces'
  id:
    | '__root__'
    | '/_authed'
    | '/(auth)/device'
    | '/(auth)/login'
    | '/_authed/_admin'
    | '/_authed/_user'
    | '/_authed/leaderboard'
    | '/_authed/'
    | '/(auth)/invite/$token'
    | '/_authed/_admin/audit-log'
    | '/_authed/_admin/dashboard'
    | '/_authed/_admin/diagnostics'
    | '/_authed/_admin/errors'
    | '/_authed/_admin/review'
    | '/_authed/_admin/security-events'
    | '/_authed/_admin/settings'
    | '/_authed/_admin/sso'
    | '/_authed/_admin/users'
    | '/_authed/_user/account'
    | '/_authed/agents/$agentId'
    | '/_authed/agents/builder'
    | '/_authed/components/$componentId'
    | '/_authed/insights/$reportId'
    | '/_authed/agents/'
    | '/_authed/components/'
    | '/_authed/wiki/'
    | '/_authed/_user/traces/$traceId'
    | '/_authed/_user/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  authDeviceRoute: typeof authDeviceRoute
  authLoginRoute: typeof authLoginRoute
  authInviteTokenRoute: typeof authInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard': {
      id: '/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_user': {
      id: '/_authed/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedUserRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/device': {
      id: '/(auth)/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof authDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/wiki/': {
      id: '/_authed/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof AuthedWikiIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/components/': {
      id: '/_authed/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof AuthedComponentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/': {
      id: '/_authed/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAgentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/insights/$reportId': {
      id: '/_authed/insights/$reportId'
      path: '/insights/$reportId'
      fullPath: '/insights/$reportId'
      preLoaderRoute: typeof AuthedInsightsReportIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/components/$componentId': {
      id: '/_authed/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof AuthedComponentsComponentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/builder': {
      id: '/_authed/agents/builder'
      path: '/agents/builder'
      fullPath: '/agents/builder'
      preLoaderRoute: typeof AuthedAgentsBuilderRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/$agentId': {
      id: '/_authed/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthedAgentsAgentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_user/account': {
      id: '/_authed/_user/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedUserAccountRouteImport
      parentRoute: typeof AuthedUserRoute
    }
    '/_authed/_admin/users': {
      id: '/_authed/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/sso': {
      id: '/_authed/_admin/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof AuthedAdminSsoRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/settings': {
      id: '/_authed/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedAdminSettingsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/security-events': {
      id: '/_authed/_admin/security-events'
      path: '/security-events'
      fullPath: '/security-events'
      preLoaderRoute: typeof AuthedAdminSecurityEventsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/review': {
      id: '/_authed/_admin/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthedAdminReviewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/errors': {
      id: '/_authed/_admin/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof AuthedAdminErrorsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/diagnostics': {
      id: '/_authed/_admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/dashboard': {
      id: '/_authed/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/audit-log': {
      id: '/_authed/_admin/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthedAdminAuditLogRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/(auth)/invite/$token': {
      id: '/(auth)/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof authInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_user/traces/': {
      id: '/_authed/_user/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof AuthedUserTracesIndexRouteImport
      parentRoute: typeof AuthedUserRoute
    }
    '/_authed/_user/traces/$traceId': {
      id: '/_authed/_user/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof AuthedUserTracesTraceIdRouteImport
      parentRoute: typeof AuthedUserRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminAuditLogRoute: typeof AuthedAdminAuditLogRoute
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedAdminDiagnosticsRoute: typeof AuthedAdminDiagnosticsRoute
  AuthedAdminErrorsRoute: typeof AuthedAdminErrorsRoute
  AuthedAdminReviewRoute: typeof AuthedAdminReviewRoute
  AuthedAdminSecurityEventsRoute: typeof AuthedAdminSecurityEventsRoute
  AuthedAdminSettingsRoute: typeof AuthedAdminSettingsRoute
  AuthedAdminSsoRoute: typeof AuthedAdminSsoRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminAuditLogRoute: AuthedAdminAuditLogRoute,
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedAdminDiagnosticsRoute: AuthedAdminDiagnosticsRoute,
  AuthedAdminErrorsRoute: AuthedAdminErrorsRoute,
  AuthedAdminReviewRoute: AuthedAdminReviewRoute,
  AuthedAdminSecurityEventsRoute: AuthedAdminSecurityEventsRoute,
  AuthedAdminSettingsRoute: AuthedAdminSettingsRoute,
  AuthedAdminSsoRoute: AuthedAdminSsoRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedUserRouteChildren {
  AuthedUserAccountRoute: typeof AuthedUserAccountRoute
  AuthedUserTracesTraceIdRoute: typeof AuthedUserTracesTraceIdRoute
  AuthedUserTracesIndexRoute: typeof AuthedUserTracesIndexRoute
}

const AuthedUserRouteChildren: AuthedUserRouteChildren = {
  AuthedUserAccountRoute: AuthedUserAccountRoute,
  AuthedUserTracesTraceIdRoute: AuthedUserTracesTraceIdRoute,
  AuthedUserTracesIndexRoute: AuthedUserTracesIndexRoute,
}

const AuthedUserRouteWithChildren = AuthedUserRoute._addFileChildren(
  AuthedUserRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedUserRoute: typeof AuthedUserRouteWithChildren
  AuthedLeaderboardRoute: typeof AuthedLeaderboardRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAgentsAgentIdRoute: typeof AuthedAgentsAgentIdRoute
  AuthedAgentsBuilderRoute: typeof AuthedAgentsBuilderRoute
  AuthedComponentsComponentIdRoute: typeof AuthedComponentsComponentIdRoute
  AuthedInsightsReportIdRoute: typeof AuthedInsightsReportIdRoute
  AuthedAgentsIndexRoute: typeof AuthedAgentsIndexRoute
  AuthedComponentsIndexRoute: typeof AuthedComponentsIndexRoute
  AuthedWikiIndexRoute: typeof AuthedWikiIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedUserRoute: AuthedUserRouteWithChildren,
  AuthedLeaderboardRoute: AuthedLeaderboardRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAgentsAgentIdRoute: AuthedAgentsAgentIdRoute,
  AuthedAgentsBuilderRoute: AuthedAgentsBuilderRoute,
  AuthedComponentsComponentIdRoute: AuthedComponentsComponentIdRoute,
  AuthedInsightsReportIdRoute: AuthedInsightsReportIdRoute,
  AuthedAgentsIndexRoute: AuthedAgentsIndexRoute,
  AuthedComponentsIndexRoute: AuthedComponentsIndexRoute,
  AuthedWikiIndexRoute: AuthedWikiIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  authDeviceRoute: authDeviceRoute,
  authLoginRoute: authLoginRoute,
  authInviteTokenRoute: authInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
